FROM python:3.11-slim

WORKDIR /app

# CPU-only PyTorch + Gradio
RUN pip install --no-cache-dir numpy && \
    pip install --no-cache-dir \
    torch==2.5.1 --index-url https://download.pytorch.org/whl/cpu && \
    pip install --no-cache-dir gradio

COPY . .

EXPOSE 7860

ENTRYPOINT ["python", "textClassifier/gui/app.py"]
